In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('cleaned_titanic_data.csv')
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Has_Cabin', 'Title', 'Family_Size', 'IsAlone', 'AgeGroup',
       'Farebins'],
      dtype='object')

In [5]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Has_Cabin,Title,Family_Size,IsAlone,AgeGroup,Farebins
0,0,3,0,22.0,1,0,7.2500,S,0,Mr,2,0,Young Adult,Low
1,1,1,1,38.0,1,0,71.2833,C,1,Mrs,2,0,Adult,Very High
2,1,3,1,26.0,0,0,7.9250,S,0,Miss,1,1,Young Adult,medium
3,1,1,1,35.0,1,0,53.1000,S,1,Mrs,2,0,Young Adult,Very High
4,0,3,0,35.0,0,0,8.0500,S,0,Mr,1,1,Young Adult,medium

In [8]:
df = pd.get_dummies(df,columns = ['Farebins','AgeGroup','Title'],dtype = int)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Has_Cabin,Family_Size,...,AgeGroup_Adult,AgeGroup_Senior,AgeGroup_Teen,AgeGroup_Young Adult,AgeGroup_child,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_rare
0,0,3,0,22.0,1,0,7.2500,S,0,2,...,0,0,0,1,0,0,0,1,0,0
1,1,1,1,38.0,1,0,71.2833,C,1,2,...,1,0,0,0,0,0,0,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,0,1,...,0,0,0,1,0,0,1,0,0,0
3,1,1,1,35.0,1,0,53.1000,S,1,2,...,0,0,0,1,0,0,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,0,1,...,0,0,0,1,0,0,0,1,0,0

In [10]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Has_Cabin', 'Family_Size', 'IsAlone', 'Farebins_High',
       'Farebins_Low', 'Farebins_Very High', 'Farebins_medium',
       'AgeGroup_Adult', 'AgeGroup_Senior', 'AgeGroup_Teen',
       'AgeGroup_Young Adult', 'AgeGroup_child', 'Title_Master', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_rare'],
      dtype='object')

In [22]:
pd.set_option('display.max_rows',None);

In [23]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Has_Cabin,Family_Size,...,AgeGroup_Adult,AgeGroup_Senior,AgeGroup_Teen,AgeGroup_Young Adult,AgeGroup_child,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_rare
0,0,3,0,22.0,1,0,7.2500,S,0,2,...,0,0,0,1,0,0,0,1,0,0
1,1,1,1,38.0,1,0,71.2833,C,1,2,...,1,0,0,0,0,0,0,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,0,1,...,0,0,0,1,0,0,1,0,0,0
3,1,1,1,35.0,1,0,53.1000,S,1,2,...,0,0,0,1,0,0,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,0,1,...,0,0,0,1,0,0,0,1,0,0

In [25]:
df.to_csv('clean_titanic_data.csv')